<?php
/**
 * CustomFieldTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * コーデンベルク APIリファレンス
 *
 * 印刷APIプラットフォーム「[コーデンベルク](https://codenberg.io/)」はさまざまなシステムと連携することができるように、WebAPIを公開しています。コーデンベルク APIを使って、印刷物の注文はもちろん、テンプレートの登録や可変領域の設定ができます。コーデンベルク APIは、RESTfulな設計なのでかんたんにシステム連携できます。
 *
 * OpenAPI spec version: 1.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Swagger\Client;

/**
 * CustomFieldTest Class Doc Comment
 *
 * @category    Class */
// * @description CustomField
/**
 * @package     Swagger\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class CustomFieldTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "CustomField"
     */
    public function testCustomField()
    {
    }

    /**
     * Test attribute "id"
     */
    public function testPropertyId()
    {
    }

    /**
     * Test attribute "name"
     */
    public function testPropertyName()
    {
    }

    /**
     * Test attribute "field_type"
     */
    public function testPropertyFieldType()
    {
    }

    /**
     * Test attribute "default_value"
     */
    public function testPropertyDefaultValue()
    {
    }

    /**
     * Test attribute "height"
     */
    public function testPropertyHeight()
    {
    }

    /**
     * Test attribute "width"
     */
    public function testPropertyWidth()
    {
    }

    /**
     * Test attribute "x"
     */
    public function testPropertyX()
    {
    }

    /**
     * Test attribute "y"
     */
    public function testPropertyY()
    {
    }

    /**
     * Test attribute "rotate"
     */
    public function testPropertyRotate()
    {
    }

    /**
     * Test attribute "page"
     */
    public function testPropertyPage()
    {
    }

    /**
     * Test attribute "is_background"
     */
    public function testPropertyIsBackground()
    {
    }

    /**
     * Test attribute "color_c"
     */
    public function testPropertyColorC()
    {
    }

    /**
     * Test attribute "color_m"
     */
    public function testPropertyColorM()
    {
    }

    /**
     * Test attribute "color_y"
     */
    public function testPropertyColorY()
    {
    }

    /**
     * Test attribute "color_k"
     */
    public function testPropertyColorK()
    {
    }

    /**
     * Test attribute "font"
     */
    public function testPropertyFont()
    {
    }

    /**
     * Test attribute "max_length"
     */
    public function testPropertyMaxLength()
    {
    }

    /**
     * Test attribute "text_align"
     */
    public function testPropertyTextAlign()
    {
    }

    /**
     * Test attribute "text_size"
     */
    public function testPropertyTextSize()
    {
    }

    /**
     * Test attribute "tracking"
     */
    public function testPropertyTracking()
    {
    }

    /**
     * Test attribute "writing_mode"
     */
    public function testPropertyWritingMode()
    {
    }

    /**
     * Test attribute "z_index"
     */
    public function testPropertyZIndex()
    {
    }
}
