<?php
/**
 * OrdersApiTest
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * コーデンベルク APIリファレンス
 *
 * 印刷APIプラットフォーム「[コーデンベルク](https://codenberg.io/)」はさまざまなシステムと連携することができるように、WebAPIを公開しています。コーデンベルク APIを使って、印刷物の注文はもちろん、テンプレートの登録や可変領域の設定ができます。コーデンベルク APIは、RESTfulな設計なのでかんたんにシステム連携できます。
 *
 * OpenAPI spec version: 1.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the endpoint.
 */

namespace Swagger\Client;

use \Swagger\Client\Configuration;
use \Swagger\Client\ApiClient;
use \Swagger\Client\ApiException;
use \Swagger\Client\ObjectSerializer;

/**
 * OrdersApiTest Class Doc Comment
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class OrdersApiTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test case for cancelOrder
     *
     * Cancel order.
     *
     */
    public function testCancelOrder()
    {
    }

    /**
     * Test case for createOrder
     *
     * Create new order from template.
     *
     */
    public function testCreateOrder()
    {
    }

    /**
     * Test case for getCancelStatus
     *
     * Get cancel order status.
     *
     */
    public function testGetCancelStatus()
    {
    }

    /**
     * Test case for getDeliveryStatus
     *
     * Get delivery address status for change.
     *
     */
    public function testGetDeliveryStatus()
    {
    }

    /**
     * Test case for getOrderById
     *
     * Get order by Id.
     *
     */
    public function testGetOrderById()
    {
    }

    /**
     * Test case for getOrders
     *
     * Get order list.
     *
     */
    public function testGetOrders()
    {
    }

    /**
     * Test case for updateDeliveryStatus
     *
     * Change delivery address.
     *
     */
    public function testUpdateDeliveryStatus()
    {
    }
}
